id: I65E287B4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-18T05:51:38+00:00'
last_modified: '2022-06-15T17:56:52.034754+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG15516
  title: དཔལ་མཉམ་མེད་མར་པ་བཀའ་བརྒྱུད་ཀྱི་གྲུབ་པའི་མཐའ་རྣམ་པར་ངེས་པར་བྱེད་པ་མདོར་བསྡུས་སུ་བརྗོད་པ་དྭགས་བརྒྱུད་གྲུབ་པའི་མེ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AF84:
      image_group_id: I1KG15583
      title: Volume 1 of dpal mnyam med mar pa bka' brgyud kyi grub pa'i mtha' rnam
        par nges par byed pa mdor bsdus su brjod pa dwags brgyud grub pa'i me long
        /
      total_pages: 382
      order: 1
      base_file: AF84.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
